### ISSUE TITLE
[BUG] Paystack Typescript import not constructable

### ISSUE THREAD

**Issue by orimdominic** [PaystackOSS/paystack-node#4]
**Describe the bug**
Cannot construct object from Paystack import after following documentation

**To Reproduce**
1. In a Node.js Typescript project, install `@paystack/paystack-sdk`
2. Import the library following the documentation
```ts
import Paystack from '@paystack/paystack-sdk';
const paystack = new Paystack('secret);
```

**Expected behavior**
There should be no errors and the returned object from the `Paystack` constructor should have autocomplete suggestions

**Screenshots**
![Screenshot from 2022-10-25 08-44-29 ](https://user-images.githubusercontent.com/37955249/197715158-f3cde3ae-1d33-4b11-bc63-a3feda08f970.png)

**Additional context**
Editor: VSCode
Node.js version: v16.17.1
Typescript version: ^4.7.4

**Comment by damilola-paystack** [comment]
Hi @orimdominic, thanks for providing context on this bug. I'll try to replicate it on my end and get back to you

**Comment by damilola-paystack** [comment]
Hi @orimdominic I've been able to replicate the bug. We'll work on a fix and push it out as soon as possible.

**Comment by damilola-paystack** [comment]
@orimdominic we've just published the fix to this issue in PR #6. Kindly upgrade to v1.0.1 and try again.  You might get an error about the resource (e.g transaction) not being a type of `paystack`, but that's just a typing error that can be ignored for now. I'll work on the types in another PR.

**Comment by waptik** [comment]
I'm still getting the error even after upgrading to v1.0.1
![image](https://user-images.githubusercontent.com/1687551/199316807-b3e82510-1fae-43c8-904c-9d7b860e4bb6.png)

**Comment by damilola-paystack** [comment]
Hey @waptik I somehow missed this. Are you still getting this error?  Should the issue be reopened?

**Comment by waptik** [comment]
> Hey @waptik I somehow missed this. Are you still getting this error? Should the issue be reopened?

Yes ooo, i am still getting that error. I think it should be reopened since it occurs at the import level

**Comment by damilola-paystack** [comment]
Can you share what your `tsconfig` looks like?

**Comment by dubems** [comment]
Bumping this up again....

I still have this issue despite using the **v1.0.1**

This is what my tsconfig looks like 

```
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
    "outDir": "./dist",
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false,
  }
}

```

cc: @damilola-paystack

**Comment by damilola-paystack** [comment]
Sincere apologies for the delay here. Q1 planning and setting up for the year pushed this further down the backlog. However, it's been prioritised now and we'll push a permanent fix in early Q2.

**Comment by daudujohn** [comment]
Hi, are there still any plans to fix this issue?

**Comment by orimdominic** [comment]
Hello @damilola-paystack Is there any resolution on this?
I am having the same issue that @waptik and @dubems are having
For context, here is information you may need and if you need more, you can make a request.

Editor: VSCode 1.82.1
Node.js version: v20.9.0
Typescript version: ^4.9.5

**Comment by R4heem-Orekoya** [comment]
Please when is this issue going to be fixed?😓

![Screenshot 2024-01-28 153937](https://github.com/PaystackOSS/paystack-node/assets/112984523/a9359f04-c682-4733-87e9-f97958105854)

**Comment by ogheneovo12** [comment]
almost two years and still not fixed

**Comment by damilola-paystack** [comment]
Hey folks, apologizing right now is literally rubbing salt on injury. For some reason, the notifications from this thread wasn't getting to our internal tool. I've assigned the issue to myself and will pick up work on it.

**Comment by orimdominic** [comment]
Hello @damilola-paystack, I have tested this with `@paystack/paystack-sdk@1.2.1-beta.1` and can confirm that the error does not come up with Typescript `5.5.2` 🚀 💪🏽 🙌🏽 
However, I do not get suggestions for methods and fields from the paystack object when created
```js
import { Paystack } from '@paystack/paystack-sdk'
const p = new Paystack("you-cant-see-me")
p. // no suggestions for methods like `charge` and `customer`
```

**Comment by damilola-paystack** [comment]
Thanks for the feedback @orimdominic. Yeah, I noticed the types aren't built after compilation. This is being looked into but we want to ensure the SDK is stable and usable first.

**Comment by steve-jr** [comment]
@damilola-paystack I tested `@paystack/paystack-sdk": "^1.2.1-beta.1` version using CJS where I get this error 
`{
  status: undefined,
  message: "'sk_test_XXXXXX' not a valid key=value pair (missing equal-sign) in Authorization header: 'Bearer sk_test_XXXXXX'.", 
  data: undefined
}`

However
```
const { Paystack } = require('@paystack/paystack-sdk')
const paystack = new Paystack("sk_test_XXXXXX")
```

**Comment by damilola-paystack** [comment]
Hey @steve-jr it seems you didn't complete typing out your feedback. Can you try update so we understand what the issue is?

**Comment by steve-jr** [comment]
> @damilola-paystack I tested with `@paystack/paystack-sdk": "^1.2.1-beta.1` version using CommonJS where I get this error `{ status: undefined, message: "'sk_test_XXXXXX' not a valid key=value pair (missing equal-sign) in Authorization header: 'Bearer sk_test_XXXXXX'.", data: undefined }`
> 
> when initializing the paystack object.
> 
> Here is a code snippet
> 
> ```
> const { Paystack } = require('@paystack/paystack-sdk')
> const paystack = new Paystack("sk_test_XXXXXX")
> ```

@damilola-paystack It is updated now.

**Comment by damilola-paystack** [comment]
This is strange @steve-jr. I tried replicating to no avail. Can you try making a direct API call in the same project without using the library?

**Comment by gray-adeyi** [comment]
Hi! try out this package. It's not yet a major release but it supports typescript and other JavaScript runtime like bun and Deno https://www.npmjs.com/package/@gray-adeyi/paystack-sdk

**Comment by gray-adeyi** [comment]
@gray-adeyi/paystack-sdk 0.2.4 release is now available with even better type support 🔥 https://www.npmjs.com/package/@gray-adeyi/paystack-sdk

**Comment by joshysmart** [comment]
This is still an issue

**Comment by gloriadasilva** [comment]
Hi @damilola-paystack , I ran into the same `Paystack is not a constructor` error. I was only able to fix it after stumbling on this thread and installing `@npm i @paystack/paystack-sdk@1.2.1-beta.1`.

The problem is that the fix currently only lives in a pre-release, so the documented `npm install @paystack/paystack-sdk` still pulls the older broken build. Anyone who doesn't find this issue hits the error with no obvious way out.

Would it be possible to promote this to a stable release so new users get the fix from the default install?

**Comment by damilola-paystack** [comment]
Thanks for bubbling this up again @gloriadasilva. We've bumped up the beta release to the main one.
